language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- docker login -u $dockerhubuser -p $dockerhubpassword docker.io
script:
- ng build --prod
- "./dockerbuild.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_59a64ada46b3_key -iv $encrypted_59a64ada46b3_iv -in id_rsa.enc -out id_rsa -d
- chmod 700 id_rsa
