language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- docker login -u $dockerhubuser -p $dockerhubpassword docker.io
script:
- ng build --prod
- "./dockerbuild.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_59a64ada46b3_key -iv $encrypted_59a64ada46b3_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 700 id_rsa
notifications:
  slack:
    secure: cN1hDoxW08pYN440VJhCp2l6CCMXfUt2NOqPMWMDsSrjJS2QfCMytpgwL7ZgBWymesuoOHeVD0bLu5bQidT1LSTJcoq0uqybtHicXSW1zKG6p+0dk855Sd0FKprEzaNWGz9Hwr4Sqkt56sXu846UpoGf6tWypZ2EURk1JCzN1pgMFd0M4cbZssi1doU6ex0t5qOlNBvdiGgubTx7PuQmtZTJqhiz6ctYCHbuXhJzda5TGsF6p47Xj4MTDkPDGd443BIWAdLThvJYPTepQjpbNehD9XufJLYhkfreQ3sv6k4K0F0z6QS6NFnsIwXdx7nUh9e/C9vHSrQXOF5nzPA5i0sj7w6AeWklL10vi9uXuTLjwr8EzG/SgoVqXDzhabQqDC7z3OBH8CbFGIIoi6e9pmDHB3RXbt3TBHAeU+4q57KmDAs12//7YdE11P80G5n9rzxvK0GxUQufuXhDq2M/6ZpWuOfBVD6D4LCVd9GAKYFabtWTGYDT2ikFNj8aH8LhIbR1SxuzO9gEg4hI+KyE5FnQVIGe3j71S/OIWCxlplACPt7hT4zIId28I9xO6UA8HBmY8wu065/xhVCrH74c/a25sGljFv2d3Qm9T6UVigYUDqy0rHbrLC2KQoTwufPiAmURJVCLpVHdldnAFb2SUoz+C4jS7AJZvA20Xlhcj64=
env:
  global:
    secure: Qt4tK1qQL3XHHHINDb2G8b2DWjx3KbjAW2yRmG6I1+aGHqsfirZIzy1lqYwUB7cxZ0aXiWVfDg8TUHQTKGYW+SVZifpdPDLbOSx5FuOb8jdIfRQ7QLDMrwnKcAROzuSh0v5B5cjUEXQEf/Dq8iq1nmQOHs9Wrp9gg6Um2FsOK5YutKWjVioPP209B8fu64WYltHAZTqXkc/ZalAfmNMzDPD+IPEEg99iJiWXiPtr16jhzqjKW1OvRdL72mZ/U3lI9IwW/WKjZ3jOEMv3DptFpy0M40kxVPUhDvvIPoc8wfBpBsQ4CIg3A2/ZN0L43C8Rk9V7T/MlgvY16MdMSI9A3vs8Rg/6lLFbil1RrRaNHD0j4pqItbRWRmbowA1hIYM1AS9zXgki82nzKs2acyWydnNK3jYoH/Szm10rCmuf17DNHeLTGiREGEcW6VsapM8D7buqTo7XkPHPJ5yr2AHSvwpXMhucs5FNmXx31Q7VF+WyOWFIJNpI6HOTgRoTdMiFhNcIkwY9zGVEU1XHcZ+zrSu5k44szrd09axHxXiBKLNf6NWH+8V99QqHVQjNDQbcyQnI6aAQiNF51Yfi0yURXR9MNiPTWcpFeaUPgULZA1YUhQ1wlmFWY72XS5t1I3/Qz2TWVhv5r94vMKKnak0CVvpb/YgVZEm3wUCKvCxgeDY=
